package com.mtgofa.carinfo.obd

/** Generic (SAE J2012) descriptions for the most common codes, with a per-group fallback. */
object Dtc {
    private val known = mapOf(
        "P0010" to "Intake camshaft position actuator circuit (bank 1)",
        "P0011" to "Intake camshaft timing over-advanced (bank 1)",
        "P0012" to "Intake camshaft timing over-retarded (bank 1)",
        "P0013" to "Exhaust camshaft position actuator circuit (bank 1)",
        "P0014" to "Exhaust camshaft timing over-advanced (bank 1)",
        "P0016" to "Crankshaft / camshaft position correlation (bank 1 sensor A)",
        "P0030" to "O2 sensor heater control circuit (B1S1)",
        "P0036" to "O2 sensor heater control circuit (B1S2)",
        "P0068" to "MAP / MAF – throttle position correlation",
        "P0087" to "Fuel rail / system pressure too low",
        "P0088" to "Fuel rail / system pressure too high",
        "P0100" to "Mass air flow circuit malfunction",
        "P0101" to "Mass air flow circuit range / performance",
        "P0102" to "Mass air flow circuit low input",
        "P0103" to "Mass air flow circuit high input",
        "P0105" to "MAP / barometric pressure circuit malfunction",
        "P0106" to "MAP / barometric pressure range / performance",
        "P0107" to "MAP / barometric pressure circuit low input",
        "P0108" to "MAP / barometric pressure circuit high input",
        "P0110" to "Intake air temperature circuit malfunction",
        "P0112" to "Intake air temperature circuit low input",
        "P0113" to "Intake air temperature circuit high input",
        "P0115" to "Engine coolant temperature circuit malfunction",
        "P0116" to "Engine coolant temperature range / performance",
        "P0117" to "Engine coolant temperature circuit low input",
        "P0118" to "Engine coolant temperature circuit high input",
        "P0120" to "Throttle position sensor A circuit malfunction",
        "P0121" to "Throttle position sensor A range / performance",
        "P0122" to "Throttle position sensor A circuit low input",
        "P0123" to "Throttle position sensor A circuit high input",
        "P0125" to "Insufficient coolant temperature for closed loop",
        "P0128" to "Coolant thermostat (below regulating temperature)",
        "P0130" to "O2 sensor circuit malfunction (B1S1)",
        "P0131" to "O2 sensor circuit low voltage (B1S1)",
        "P0132" to "O2 sensor circuit high voltage (B1S1)",
        "P0133" to "O2 sensor slow response (B1S1)",
        "P0134" to "O2 sensor no activity detected (B1S1)",
        "P0135" to "O2 sensor heater circuit malfunction (B1S1)",
        "P0136" to "O2 sensor circuit malfunction (B1S2)",
        "P0137" to "O2 sensor circuit low voltage (B1S2)",
        "P0138" to "O2 sensor circuit high voltage (B1S2)",
        "P0140" to "O2 sensor no activity detected (B1S2)",
        "P0141" to "O2 sensor heater circuit malfunction (B1S2)",
        "P0171" to "System too lean (bank 1)",
        "P0172" to "System too rich (bank 1)",
        "P0174" to "System too lean (bank 2)",
        "P0175" to "System too rich (bank 2)",
        "P0190" to "Fuel rail pressure sensor circuit malfunction",
        "P0200" to "Injector circuit malfunction",
        "P0201" to "Injector circuit malfunction – cylinder 1",
        "P0202" to "Injector circuit malfunction – cylinder 2",
        "P0203" to "Injector circuit malfunction – cylinder 3",
        "P0204" to "Injector circuit malfunction – cylinder 4",
        "P0217" to "Engine over-temperature condition",
        "P0218" to "Transmission fluid over-temperature condition",
        "P0219" to "Engine overspeed condition",
        "P0220" to "Throttle position sensor B circuit malfunction",
        "P0221" to "Throttle position sensor B range / performance",
        "P0234" to "Turbo / supercharger overboost condition",
        "P0299" to "Turbo / supercharger underboost",
        "P0300" to "Random / multiple cylinder misfire detected",
        "P0301" to "Cylinder 1 misfire detected",
        "P0302" to "Cylinder 2 misfire detected",
        "P0303" to "Cylinder 3 misfire detected",
        "P0304" to "Cylinder 4 misfire detected",
        "P0305" to "Cylinder 5 misfire detected",
        "P0306" to "Cylinder 6 misfire detected",
        "P0307" to "Cylinder 7 misfire detected",
        "P0308" to "Cylinder 8 misfire detected",
        "P0325" to "Knock sensor 1 circuit malfunction (bank 1)",
        "P0327" to "Knock sensor 1 circuit low input (bank 1)",
        "P0328" to "Knock sensor 1 circuit high input (bank 1)",
        "P0335" to "Crankshaft position sensor A circuit malfunction",
        "P0336" to "Crankshaft position sensor A range / performance",
        "P0340" to "Camshaft position sensor A circuit malfunction (bank 1)",
        "P0341" to "Camshaft position sensor A range / performance (bank 1)",
        "P0351" to "Ignition coil A primary / secondary circuit",
        "P0352" to "Ignition coil B primary / secondary circuit",
        "P0353" to "Ignition coil C primary / secondary circuit",
        "P0354" to "Ignition coil D primary / secondary circuit",
        "P0400" to "Exhaust gas recirculation flow malfunction",
        "P0401" to "Exhaust gas recirculation flow insufficient",
        "P0402" to "Exhaust gas recirculation flow excessive",
        "P0403" to "Exhaust gas recirculation circuit malfunction",
        "P0411" to "Secondary air injection incorrect flow",
        "P0420" to "Catalyst system efficiency below threshold (bank 1)",
        "P0421" to "Warm-up catalyst efficiency below threshold (bank 1)",
        "P0430" to "Catalyst system efficiency below threshold (bank 2)",
        "P0440" to "Evaporative emission control system malfunction",
        "P0441" to "EVAP system incorrect purge flow",
        "P0442" to "EVAP system small leak detected",
        "P0443" to "EVAP purge control valve circuit",
        "P0446" to "EVAP vent control circuit malfunction",
        "P0455" to "EVAP system large leak detected",
        "P0456" to "EVAP system very small leak detected",
        "P0480" to "Cooling fan 1 control circuit malfunction",
        "P0500" to "Vehicle speed sensor malfunction",
        "P0505" to "Idle control system malfunction",
        "P0506" to "Idle control system RPM lower than expected",
        "P0507" to "Idle control system RPM higher than expected",
        "P0520" to "Engine oil pressure sensor / switch circuit",
        "P0562" to "System voltage low",
        "P0563" to "System voltage high",
        "P0571" to "Brake switch A circuit malfunction",
        "P0600" to "Serial communication link malfunction",
        "P0601" to "Internal control module memory checksum error",
        "P0603" to "Internal control module keep-alive memory (KAM) error",
        "P0604" to "Internal control module RAM error",
        "P0605" to "Internal control module ROM error",
        "P0606" to "ECM / PCM processor fault",
        "P0700" to "Transmission control system malfunction",
        "P0705" to "Transmission range sensor circuit malfunction",
        "P0715" to "Input / turbine speed sensor circuit malfunction",
        "P0720" to "Output speed sensor circuit malfunction",
        "P0730" to "Incorrect gear ratio",
        "P0740" to "Torque converter clutch circuit malfunction",
        "P0750" to "Shift solenoid A malfunction",
        "P0755" to "Shift solenoid B malfunction",
        "P2096" to "Post-catalyst fuel trim system too lean (bank 1)",
        "P2097" to "Post-catalyst fuel trim system too rich (bank 1)",
        "P2135" to "Throttle / pedal position sensor A/B voltage correlation",
        "P2138" to "Throttle / pedal position sensor D/E voltage correlation",
        "P2187" to "System too lean at idle (bank 1)",
        "P2188" to "System too rich at idle (bank 1)",
        "P2195" to "O2 sensor signal stuck lean (B1S1)",
        "P2196" to "O2 sensor signal stuck rich (B1S1)",
        "P2270" to "O2 sensor signal stuck lean (B1S2)",
        "P2271" to "O2 sensor signal stuck rich (B1S2)",
        "U0001" to "High speed CAN communication bus",
        "U0073" to "Control module communication bus A off",
        "U0100" to "Lost communication with ECM / PCM",
        "U0101" to "Lost communication with TCM",
        "U0121" to "Lost communication with ABS control module",
        "U0140" to "Lost communication with body control module",
        "U0155" to "Lost communication with instrument cluster",
    )

    fun system(code: String): String = when (code.firstOrNull()) {
        'P' -> "Powertrain"
        'C' -> "Chassis"
        'B' -> "Body"
        'U' -> "Network"
        else -> "Unknown"
    }

    fun describe(code: String): String {
        known[code]?.let { return it }
        val manufacturer = code.getOrNull(1) == '1' || code.getOrNull(1) == '3'
        val group = if (code.startsWith("P")) when (code.getOrNull(2)) {
            '0', '1', '2' -> "Fuel and air metering"
            '3' -> "Ignition system or misfire"
            '4' -> "Auxiliary emission controls"
            '5' -> "Vehicle speed, idle control and auxiliary inputs"
            '6' -> "Computer output circuit"
            '7', '8', '9' -> "Transmission"
            'A', 'B', 'C' -> "Hybrid propulsion"
            else -> "Powertrain"
        } else system(code)
        return if (manufacturer) "$group (manufacturer specific)" else group
    }
}
